apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/flyflame/order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9002
          env:
            # spring boot Relaxed binding
            - name: POLAR_CATALOG_SERVICE_URI
              value: http://catalog-service
            - name: SPRING_CONFIG_URI
              value: http://config-service
            - name: SPRING_R2DBC_URL
              # no need to specify port because k8s service, for more lookup: polar-deployment/kubernetes/platform/development/services/postgresql.yml
              value: r2dbc:postgresql://polar-postgres/polardb_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://polar-postgres/polardb_order